export const SHOWSPIN = 'SHOWSPIN';
export const HIDDENSPIN = 'HIDDENSPIN';
export const GETTOPSALLDATA = 'GETTOPSALLDATA';
export const GETDETAILDATA = 'GETDETAILDATA';
export const GETUSERSDATA = 'GETUSERSDATA';